export const demoProducts = [
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 1,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 2,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 3,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 4,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 5,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 6,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 7,
   },
   {
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      name: "Denim Jeans",
      added: "EMart Retailers",
      rating: "4 ratings",
      price: 400,
      id: 8,
   },
];
